# Generated by Django 4.2.14 on 2026-06-02 07:36

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_module_company_module_settings_alter_module_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Código")),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Activo"),
                            ("liability", "Pasivo"),
                            ("equity", "Patrimonio"),
                            ("income", "Ingreso"),
                            ("expense", "Gasto"),
                            ("bank", "Banco / Efectivo"),
                        ],
                        default="asset",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("notes", models.TextField(blank=True, verbose_name="Notas")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="core.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Contable",
                "verbose_name_plural": "Cuentas Contables",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Número de Factura"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("sale", "Factura de Venta"),
                            ("purchase", "Factura de Compra"),
                            ("credit", "Nota de Crédito"),
                            ("debit", "Nota de Débito"),
                        ],
                        default="sale",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Emisión",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("posted", "Registrado"),
                            ("paid", "Pagado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "uuid_fiscal",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID legal del comprobante fiscal (CFDI/FEL/etc.)",
                        verbose_name="UUID Fiscal",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="facturacion/pdf/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "xml_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="facturacion/xml/",
                        verbose_name="XML / CFDI",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="Total"
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Saldo Pendiente",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notas / Términos"),
                ),
                (
                    "internal_note",
                    models.TextField(blank=True, verbose_name="Nota Interna"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("code", models.CharField(max_length=10, verbose_name="Código")),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("sale", "Ventas"),
                            ("purchase", "Compras"),
                            ("bank", "Banco"),
                            ("cash", "Efectivo"),
                            ("general", "Diario General"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "sequence",
                    models.PositiveIntegerField(default=10, verbose_name="Orden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="core.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "default_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_journals",
                        to="modulo_facturacion.account",
                        verbose_name="Cuenta Predeterminada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diario Contable",
                "verbose_name_plural": "Diarios Contables",
                "ordering": ["sequence", "name"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referencia"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("posted", "Confirmado")],
                        default="draft",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("narration", models.TextField(blank=True, verbose_name="Narración")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="core.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entry",
                        to="modulo_facturacion.invoice",
                        verbose_name="Factura Origen",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="modulo_facturacion.journal",
                        verbose_name="Diario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento Contable",
                "verbose_name_plural": "Asientos Contables",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre / Razón social"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="RFC / RUC / NIT"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("customer", "Cliente"),
                            ("supplier", "Proveedor"),
                            ("both", "Ambos"),
                        ],
                        default="customer",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partners",
                        to="core.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto",
                "verbose_name_plural": "Contactos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JournalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Débito",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Crédito",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_items",
                        to="modulo_facturacion.account",
                        verbose_name="Cuenta",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="modulo_facturacion.journalentry",
                        verbose_name="Asiento",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="modulo_facturacion.partner",
                        verbose_name="Contacto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apunte Contable",
                "verbose_name_plural": "Apuntes Contables",
                "ordering": ["entry", "id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=255, verbose_name="Concepto / Producto"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=12,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Precio Unitario",
                    ),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("16.00"),
                        max_digits=5,
                        verbose_name="% Impuesto",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="% Descuento",
                    ),
                ),
                (
                    "amount_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Subtotal Línea",
                    ),
                ),
                (
                    "amount_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="IVA Línea",
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Total Línea",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_lines",
                        to="modulo_facturacion.account",
                        verbose_name="Cuenta Contable",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="modulo_facturacion.invoice",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de Factura",
                "verbose_name_plural": "Líneas de Factura",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceChatter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("note", "Nota"),
                            ("change", "Cambio de Estado"),
                            ("system", "Sistema"),
                            ("message", "Mensaje"),
                        ],
                        default="note",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("body", models.TextField(verbose_name="Contenido")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chatter_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatter",
                        to="modulo_facturacion.invoice",
                        verbose_name="Factura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje del Chatter",
                "verbose_name_plural": "Mensajes del Chatter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="modulo_facturacion.journal",
                verbose_name="Diario",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="modulo_facturacion.partner",
                verbose_name="Cliente / Proveedor",
            ),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la cuenta"
                    ),
                ),
                ("bank_name", models.CharField(max_length=100, verbose_name="Banco")),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número de cuenta / CLABE",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("MXN", "Peso Mexicano (MXN)"),
                            ("PEN", "Sol Peruano (PEN)"),
                            ("USD", "Dólar Americano (USD)"),
                            ("COP", "Peso Colombiano (COP)"),
                            ("EUR", "Euro (EUR)"),
                            ("GTQ", "Quetzal Guatemalteco (GTQ)"),
                        ],
                        default="MXN",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="modulo_facturacion.account",
                        verbose_name="Cuenta Contable",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="core.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_accounts",
                        to="modulo_facturacion.journal",
                        verbose_name="Diario Bancario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta Bancaria",
                "verbose_name_plural": "Cuentas Bancarias",
                "ordering": ["bank_name", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "state"], name="modulo_fact_company_3adc0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "invoice_type"],
                name="modulo_fact_company_076367_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["company", "date"], name="modulo_fact_company_fa1fbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["company", "account_type"],
                name="modulo_fact_company_2879bb_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("company", "code")},
        ),
    ]
