# Generated by Django 4.2.14 on 2026-05-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_task_event_timeentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="core.company",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="settings",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Ajustes del módulo"
            ),
        ),
        migrations.AlterField(
            model_name="module",
            name="slug",
            field=models.SlugField(verbose_name="Slug"),
        ),
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("company", "slug")},
        ),
    ]
