# Generated by Django 4.2.14 on 2026-05-23 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_task_event_timeentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comanda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("folio", models.CharField(max_length=20, verbose_name="Folio")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_cocina", "En Cocina"),
                            ("lista", "Lista para Servir"),
                            ("servida", "Servida"),
                            ("pagada", "Pagada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="abierta",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "comensales",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Comensales"
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Notas")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Total"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pagada_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pagada en"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comandas",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comanda",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mesa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(verbose_name="Número de Mesa"),
                ),
                (
                    "nombre",
                    models.CharField(blank=True, max_length=50, verbose_name="Nombre"),
                ),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="Capacidad"
                    ),
                ),
                (
                    "zona",
                    models.CharField(
                        blank=True,
                        default="Principal",
                        max_length=50,
                        verbose_name="Zona",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("ocupada", "Ocupada"),
                            ("reservada", "Reservada"),
                            ("cuenta", "Pidiendo Cuenta"),
                            ("limpieza", "En Limpieza"),
                        ],
                        default="libre",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mesas",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesa",
                "ordering": ["numero"],
                "unique_together": {("company", "numero")},
            },
        ),
        migrations.CreateModel(
            name="ItemComanda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=8,
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "precio_unit",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Subtotal"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_cocina", "En Cocina"),
                            ("listo", "Listo"),
                            ("servido", "Servido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "notas",
                    models.CharField(blank=True, max_length=255, verbose_name="Notas"),
                ),
                ("cancelado", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comanda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="restaurante.comanda",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Comanda",
            },
        ),
        migrations.AddField(
            model_name="comanda",
            name="mesa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comandas",
                to="restaurante.mesa",
            ),
        ),
        migrations.AddField(
            model_name="comanda",
            name="mesero",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comandas_mesero",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
