# Generated by Django 4.2.14 on 2026-05-30 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_module_company_module_settings_alter_module_slug_and_more"),
        ("modulo_web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webcontact",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="webpage",
            options={"ordering": ["order", "slug"]},
        ),
        migrations.AddField(
            model_name="webpage",
            name="is_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="webpage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="WebSiteConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("header_html", models.TextField(blank=True, default="")),
                ("header_css", models.TextField(blank=True, default="")),
                ("header_components", models.JSONField(blank=True, default=dict)),
                ("footer_html", models.TextField(blank=True, default="")),
                ("footer_css", models.TextField(blank=True, default="")),
                ("footer_components", models.JSONField(blank=True, default=dict)),
                ("global_css", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_config",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del sitio",
            },
        ),
    ]
